// examples/react/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import type { CapacitorUserManager, User } from 'capacitor-oidc';

import { completeWebCallback, getUserManager } from './auth';

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

export function App() {
  const auth = useRef<CapacitorUserManager | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('Restoring the stored session…');
  const displayName = user?.profile.preferred_username ?? user?.profile.name ?? user?.profile.sub;

  useEffect(() => {
    let active = true;
    let manager: CapacitorUserManager | undefined;
    const userLoaded = (loadedUser: User) => {
      if (!active) return;
      setUser(loadedUser);
      setMessage('The session was stored.');
    };
    const userUnloaded = () => {
      if (!active) return;
      setUser(null);
      setMessage('The session was cleared.');
    };

    void getUserManager()
      .then(async (currentManager) => {
        if (!active) return;
        manager = currentManager;
        auth.current = currentManager;
        currentManager.events.addUserLoaded(userLoaded);
        currentManager.events.addUserUnloaded(userUnloaded);

        await completeWebCallback(currentManager);
        const storedUser = await currentManager.getUser();
        if (!active) return;
        setUser(storedUser);
        setMessage(storedUser ? 'The stored session is ready.' : 'No local session is stored.');
      })
      .catch((error: unknown) => {
        if (active) setMessage(errorMessage(error));
      });

    return () => {
      active = false;
      auth.current = null;
      manager?.events.removeUserLoaded(userLoaded);
      manager?.events.removeUserUnloaded(userUnloaded);
    };
  }, []);

  function run(label: string, action: () => Promise<void>) {
    setBusy(true);
    setMessage(label);
    void action()
      .catch((error: unknown) => setMessage(errorMessage(error)))
      .finally(() => setBusy(false));
  }

  function signin() {
    const manager = auth.current;
    if (manager) run('Opening the identity provider…', () => manager.signin());
  }

  function renew() {
    const manager = auth.current;
    if (!manager) return;

    run('Renewing the session…', async () => {
      const renewedUser = await manager.getValidUser(60);
      setUser(renewedUser);
      setMessage(renewedUser ? 'The access token is ready.' : 'No renewable session was found.');
    });
  }

  function signout() {
    const manager = auth.current;
    if (manager) run('Signing out at the identity provider…', () => manager.signout());
  }

  return (
    <main>
      <section className="card" aria-labelledby="title">
        <p className="eyebrow">React + Capacitor</p>
        <h1 id="title">OpenID Connect, one manager</h1>
        <p className="summary">The same session API runs in the browser and in the native Capacitor shell.</p>

        <div className="session" aria-live="polite">
          <span className={`status-dot${user ? ' active' : ''}`} aria-hidden="true" />
          <div>
            <strong>{user ? `Signed in as ${displayName}` : 'Signed out'}</strong>
            <p>{message}</p>
          </div>
        </div>

        <div className="actions">
          <button disabled={busy || !auth.current || Boolean(user)} onClick={signin}>
            Sign in
          </button>
          <button className="secondary" disabled={busy || !user} onClick={renew}>
            Renew
          </button>
          <button className="secondary" disabled={busy || !user} onClick={signout}>
            Sign out
          </button>
        </div>
      </section>
    </main>
  );
}

// examples/angular/src/app/app.component.ts
import { ChangeDetectionStrategy, Component, inject, OnInit } from '@angular/core';

import { OidcService } from './oidc.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent implements OnInit {
  readonly oidc = inject(OidcService);

  ngOnInit() {
    void this.oidc.initialize().catch((error: unknown) => {
      this.oidc.message.set(error instanceof Error ? error.message : String(error));
    });
  }
}

<main>
  <section class="card" aria-labelledby="title">
    <p class="eyebrow">Angular + Capacitor</p>
    <h1 id="title">OpenID Connect, one manager</h1>
    <p class="summary">The same session API runs in the browser and in the native Capacitor shell.</p>

    <div class="session" aria-live="polite">
      <span class="status-dot" [class.active]="oidc.user()" aria-hidden="true"></span>
      <div>
        <strong>{{ oidc.user() ? `Signed in as ${oidc.displayName()}` : 'Signed out' }}</strong>
        <p>{{ oidc.message() }}</p>
      </div>
    </div>

    <div class="actions">
      <button [disabled]="oidc.busy() || !oidc.ready() || !!oidc.user()" (click)="oidc.signin()">Sign in</button>
      <button class="secondary" [disabled]="oidc.busy() || !oidc.user()" (click)="oidc.renew()">Renew</button>
      <button class="secondary" [disabled]="oidc.busy() || !oidc.user()" (click)="oidc.signout()">Sign out</button>
    </div>
  </section>
</main>
