// examples/vue/src/App.vue
<script setup lang="ts">
import { computed, onMounted, ref, shallowRef } from 'vue';
import type { CapacitorUserManager, User } from 'capacitor-oidc';

import { getUserManager } from './auth';

const auth = shallowRef<CapacitorUserManager>();
const user = shallowRef<User | null>(null);
const busy = ref(false);
const message = ref('Restoring the stored session…');
const displayName = computed(
  () => user.value?.profile.preferred_username ?? user.value?.profile.name ?? user.value?.profile.sub,
);

function report(error: unknown) {
  message.value = error instanceof Error ? error.message : String(error);
  busy.value = false;
}

function run(label: string, action: () => Promise<void>) {
  busy.value = true;
  message.value = label;
  void action()
    .catch(report)
    .finally(() => {
      busy.value = false;
    });
}

function signin() {
  const manager = auth.value;
  if (manager) run('Opening the identity provider…', () => manager.signin());
}

function renew() {
  const manager = auth.value;
  if (!manager) return;

  run('Renewing the session…', async () => {
    user.value = await manager.getValidUser(60);
    message.value = user.value ? 'The access token is ready.' : 'No renewable session was found.';
  });
}

function signout() {
  const manager = auth.value;
  if (manager) run('Signing out at the identity provider…', () => manager.signout());
}

onMounted(() => {
  void getUserManager()
    .then(async (manager) => {
      auth.value = manager;
      manager.events.addUserLoaded((loadedUser) => {
        user.value = loadedUser;
        message.value = 'The session was stored.';
      });
      manager.events.addUserUnloaded(() => {
        user.value = null;
        message.value = 'The session was cleared.';
      });

      if (window.location.pathname === '/callback') {
        await manager.signinCallback();
        window.history.replaceState({}, '', '/');
      } else if (window.location.pathname === '/logout-callback') {
        await manager.signoutCallback();
        window.history.replaceState({}, '', '/');
      }

      user.value = await manager.getUser();
      message.value = user.value ? 'The stored session is ready.' : 'No local session is stored.';
    })
    .catch(report);
});
</script>

<template>
  <main>
    <section class="card" aria-labelledby="title">
      <p class="eyebrow">Vue + Capacitor</p>
      <h1 id="title">OpenID Connect, one manager</h1>
      <p class="summary">The same session API runs in the browser and in the native Capacitor shell.</p>

      <div class="session" aria-live="polite">
        <span class="status-dot" :class="{ active: user }" aria-hidden="true"></span>
        <div>
          <strong>{{ user ? `Signed in as ${displayName}` : 'Signed out' }}</strong>
          <p>{{ message }}</p>
        </div>
      </div>

      <div class="actions">
        <button :disabled="busy || !auth || Boolean(user)" @click="signin">Sign in</button>
        <button class="secondary" :disabled="busy || !user" @click="renew">Renew</button>
        <button class="secondary" :disabled="busy || !user" @click="signout">Sign out</button>
      </div>
    </section>
  </main>
</template>

// examples/react/src/App.tsx
import { useEffect, useRef, useState } from 'react';
import type { CapacitorUserManager, User } from 'capacitor-oidc';

import { getUserManager } from './auth';

function errorMessage(error: unknown) {
  return error instanceof Error ? error.message : String(error);
}

export function App() {
  const auth = useRef<CapacitorUserManager | null>(null);
  const [user, setUser] = useState<User | null>(null);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('Restoring the stored session…');
  const displayName = user?.profile.preferred_username ?? user?.profile.name ?? user?.profile.sub;

  useEffect(() => {
    void getUserManager()
      .then(async (manager) => {
        auth.current = manager;
        manager.events.addUserLoaded((loadedUser) => {
          setUser(loadedUser);
          setMessage('The session was stored.');
        });
        manager.events.addUserUnloaded(() => {
          setUser(null);
          setMessage('The session was cleared.');
        });

        if (window.location.pathname === '/callback') {
          await manager.signinCallback();
          window.history.replaceState({}, '', '/');
        } else if (window.location.pathname === '/logout-callback') {
          await manager.signoutCallback();
          window.history.replaceState({}, '', '/');
        }

        const storedUser = await manager.getUser();
        setUser(storedUser);
        setMessage(storedUser ? 'The stored session is ready.' : 'No local session is stored.');
      })
      .catch((error: unknown) => setMessage(errorMessage(error)));
  }, []);

  function run(label: string, action: () => Promise<void>) {
    setBusy(true);
    setMessage(label);
    void action()
      .catch((error: unknown) => setMessage(errorMessage(error)))
      .finally(() => setBusy(false));
  }

  function signin() {
    const manager = auth.current;
    if (manager) run('Opening the identity provider…', () => manager.signin());
  }

  function renew() {
    const manager = auth.current;
    if (!manager) return;

    run('Renewing the session…', async () => {
      const renewedUser = await manager.getValidUser(60);
      setUser(renewedUser);
      setMessage(renewedUser ? 'The access token is ready.' : 'No renewable session was found.');
    });
  }

  function signout() {
    const manager = auth.current;
    if (manager) run('Signing out at the identity provider…', () => manager.signout());
  }

  return (
    <main>
      <section className="card" aria-labelledby="title">
        <p className="eyebrow">React + Capacitor</p>
        <h1 id="title">OpenID Connect, one manager</h1>
        <p className="summary">
          The same session API runs in the browser and in the native Capacitor shell.
        </p>

        <div className="session" aria-live="polite">
          <span className={`status-dot${user ? ' active' : ''}`} aria-hidden="true" />
          <div>
            <strong>{user ? `Signed in as ${displayName}` : 'Signed out'}</strong>
            <p>{message}</p>
          </div>
        </div>

        <div className="actions">
          <button disabled={busy || !auth.current || Boolean(user)} onClick={signin}>
            Sign in
          </button>
          <button className="secondary" disabled={busy || !user} onClick={renew}>
            Renew
          </button>
          <button className="secondary" disabled={busy || !user} onClick={signout}>
            Sign out
          </button>
        </div>
      </section>
    </main>
  );
}
